LostRuins/koboldcpp

llama_for_kobold.py

This commit changes the amount of cores to match the amount of cores in use by the system to speed up generation (If desired we could also lower this by 1 to leave one core for the user to use other applications).
I have also chanced the initialization value to 2048 since that is what most users normally prefer, this allows us to trim the data elsewhere such as the UI itself. It does seem faster on lower contexts, so ideally in a future commit we reload the model when the context is changed.

2048 context all core

---

expose.cpp

Not sure if this right but currently get this when trying to compile on Linux.
```
expose.cpp: In function ‘bool load_model(load_model_inputs)’:
expose.cpp:39:33: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
39 |         putenv(platformenv.c_str());
|                ~~~~~~~~~~~~~~~~~^~
|                                 |
|                                 const char*
In file included from /usr/include/c++/12.2.1/cstdlib:75,
from /usr/include/c++/12.2.1/ext/string_conversions.h:41,
from /usr/include/c++/12.2.1/bits/basic_string.h:3960,
from /usr/include/c++/12.2.1/string:53,
from /usr/include/c++/12.2.1/bits/locale_classes.h:40,
from /usr/include/c++/12.2.1/bits/ios_base.h:41,
from /usr/include/c++/12.2.1/ios:42,
from /usr/include/c++/12.2.1/istream:38,
from …
```

Fix make compile error in expose.cpp(?)

---

ggml_blas_adapter.c

Didn't manage to set up caching yet. I improved some steps, but the difference wasn't big.

Improve ClBlast implementation, avoid recreating buffers, remove redundant transfers

---

README.md

I encountered difficulties while trying to compile the various Windows libraries that the project depends on. To assist future developers facing the same challenge, I've updated the README with clearer instructions and guidance on building these libraries on Windows systems.
This enhancement includes tips and relevant resource links to make the process more straightforward and accessible for other developers working on the project.

[README] Improved instructions for building dependent libraries on Windows

---

.gitignore
koboldcpp.py

Hey, @LostRuins. Thanks for an awesome project.
This PR adds `--mlock` argument to koboldcpp. Without it, koboldcpp works very very slowly on my Apple M1 notebook. It's clear that it doesn't use available memory and CPU power because it moves everything into the swap file for some reason.
With `--mlock` koboldcpp starts to work quite fast on my notebook and utilizes 4 of 8 cores for 100% percent. 
Issues related to it:
https://github.com/LostRuins/koboldcpp/issues/54
https://github.com/LostRuins/koboldcpp/issues/28
P.S.
My editor has also automatically removed all the unnecessary spaces and I've added `koboldcpp.so` and
`koboldcpp_noavx2.so` to `.gitignore` so they won't be accidentally committed.

Adds --mlock argument

---

expose.h
gpttype_adapter.cpp
koboldcpp.py

This makes the (new) mirostat sampler from https://github.com/ggerganov/llama.cpp/pull/1126 available. There are more sampling techniques and features in that pull request.
I'm not sure if i implemented this correctly, so have a look at it before merging ;-) This only applies to llama.

add new sampling algorithm "mirostat"

---

.gitignore
Makefile
ggml-metal.m.diff

Using a patch file, change ggml-metal.metal path as hard-wired relative style due to lack of NSBundle environment. This will resolve issue #216.

[Enhancement] Add support for Metal inference

---

gpttype_adapter.cpp

https://github.com/LostRuins/koboldcpp/blob/b617f2847b5914736ccf65bec22caaf49b39c0a8/gpttype_adapter.cpp#LL952
```
gpttype_adapter.cpp: In function 'generation_outputs gpttype_generate(generation_inputs, generation_outputs&)':
gpttype_adapter.cpp:952:15: error: format not a string literal and no format arguments [-Werror=format-security]
952 |         printf(outstr.c_str());
|         ~~~~~~^~~~~~~~~~~~~~~~
```

Fix format string vulnerability

---

Makefile

Tested on Ubuntu 23.04 CUDA 12.1, successfully loads and runs ggml v3 model on the GPU.
I added `ggml_v2-cuda.o` otherwise the final library's missing symbols - though I don't know how useful CUDA is in the v2. Ripping out/excluding `otherarch/` from all the CUBLAS stuff seemed like a bunch more work.
I did try to use **cmake** as suggested, however it doesn't work and I didn't want to debug it:
```
-- ============== ============== ==============
-- WARNING! Do NOT use this file. It is UNSUPPORTED for normal users. Use MAKE instead.
-- It is ONLY for CUBLAS build testing on windows visual studio. IT WILL NOT BE UPDATED OR MAINTAINED !!!
-- IF YOU ARE SEEING THIS, you MUST ONLY be building AN EXPERIMENAL WINDOWS CUBLAS BUILD! NOTHING ELSE WILL BE SUPPORTED !!!
-- ============== …
```

Fix Makefile for CUBLAS.

---

Makefile
koboldcpp.py

Makefile flags are copied right from llama.cpp's Makefile.

Fix hordeconfig max context setting, and add Makefile flags for cuda F16/KQuants per iter.

---

ggml-cuda.cu

You are trying to reassign a const, causing a compile error. This fixes it by not making it a const anymore.

Fix CUDA Compilation

---

koboldcpp.py

Fixes #357.
When streaming is used, the headers are sent twice (once in `handle_sse_stream`, once in `do_POST`), which might cause the second batch of headers to be flushed into a subsequent request, causing JSON parsing errors. This occurs especially when the request was aborted (which is SillyTavern's behaviour.)
Since the headers are already sent in `handle_sse_stream`, we'll simply not send them in `do_POST`.

Fix: don't send headers twice when streaming

---

otherarch/llama_v3.cpp

These changes allow 34B codellama (both the base meta instruct & the phind finetune) to run on my system using GGML files. I haven't tested using any sort of GPU acceleration, but at least it's better than before (would crash upon attempting to load such files).

Add support for 34B GGML models

---

koboldcpp.py

"You don't have to be constantly checking for new tokens, it performs much better to wait a bit and do them in bulk, otherwise the SSE handle task wastes a bunch of time doing nothing
this fix seems to bring streaming performance in line with non streaming performance on my machine. Too lazy to pr, someone show it to them"
Not my fix, this was created by a /lmg/ user, seemed important though

Streaming performance improvements

---

ggml-opencl.cpp
gpttype_adapter.cpp
otherarch/ggml_v1.c
otherarch/ggml_v2-opencl.cpp
otherarch/ggml_v2.c
otherarch/gpt2_v2.cpp
otherarch/gptj_v2.cpp
otherarch/gptj_v3.cpp
otherarch/llama_v3.h
otherarch/rwkv_v2.cpp

Reduced the amount of warnings when building (at least with gcc on linux)
- Fixed a bunch of format specifiers to match the appropriate types.
- Removed some deprecation markers for code that depends on snapshots of old code.
Please re-test on windows.
There are still some warnings left, some attribute stuff I don't understand, and some real deprecation warnings for things upstream is presumably going to remove at some point.

Reduce warnings.

---

ggml-metal.m

I'm not familiar with Objective-C so it may be hacky, but the basic outline is there. This should probably be propagated back into llama.cpp, but I'm leaving that as an excise for someone else.

Check Metal MTLCommandBufferStatus error codes and report an out of memory error if one occurred

---

koboldcpp.py

subprocess.Popen() needs to be either used with `with:` or have `.wait()` called or be destroyed using `del` – otherwise the child process stays as a zombie process after exiting, until the object is GC'd.
subprocess.run() does the necessary .wait() automatically. (It's a convenience wrapper available from Python 3.6.)
Since shell=True is used and none of the subprocess-specific features are used, it might be even simpler to use `os.system()` (available everywhere).

avoid leaving a zombie process for --onready

---

koboldcpp.py

The current OpenAI-like API uses hardcoded chat templates. This PR implements a non-breaking adapter users can exploit to use models requiring various chat templates. Testing request against [Mistral7B Doplhin](https://huggingface.co/TheBloke/dolphin-2.0-mistral-7B-GGUF):
```json
{
"temperature": 0.5,
"max_tokens": 1024,
"messages": [
{
"role": "system",
"content": "You roleplay as a dungeon master engaged in a session of Dungeons and Dragons with the user. Write in an immersive way to avoid spoiling the user's experience."
},
{
"role": "user",
"content": "I am a kobold named Nico, what should I do?"
}
],
"adapter": {
"templates": {
"system": {
"start": "<|im_start|>system\n",
"end": "<|im_end|>\n"
},
"user": {
"start": "<|im_start|>user\n",
"end": "<|im_end|>\n"
},
"assistent": { …
```

OpenAI compat API adapter

---

.gitignore
koboldcpp.py

2 things here:
1. A .gitignore update to ignore the .idea folder created by Jet Brains IDEs. 
2. Exposing tensor split to the UI so folks can have more control of VRAM in a multi-GPU environment. If the box is not populated it will just work as before the box existed.

Tensor split UI

---

gpttype_adapter.cpp

The Top K is being forced to 120 when 'disabled' for all models, even when the value is set to zero. This means you effectively disable Top K unless Mirostat is turned on. This is a problem for reproducability reasons. It might also affect other samplers like Tail Free Sampling from working as intended as they come later in the sampler stack.
The fix for this is as simple as setting the value to the current model's vocabulary size.

Fix for Top K disabling

---

README.md

This PR adds the following:
- Instructions for the koboldcpp Arch User Repository (AUR) packages
- ~~Clean up the preview images by placing them in a 2x2 table~~
No hidden dev fees were sneaked into the PR

readme: add AUR instructions and clean up preview

---

.gitignore
environment.yaml
koboldcpp.sh

Something I am very excited to add, my specialty MicroMamba runtime now for Koboldcpp!
This makes it much simpler for Linux users to get going, complete with 3 modes.
Mode 1: koboldcpp.sh as a substitute for koboldcpp.py, it will ensure all the dependencies are installed (You do need wget, and bzip2 for it to function), automatically compiles all the libs and then launches koboldcpp with its own internal python.
Mode 2: koboldcpp.sh dist : This automatically generates an experimental pyinstaller build, These seem to work across a wide range of Linux distributions if compiled on Ubuntu 18.04 (See my releases). If a user has an incompatible distro chances are it does work if they run the command themselves to generate a binary for their libs.
Mode 3: koboldcpp.sh rebuild : This triggers a …

koboldcpp.sh - The Mamba Multitool

---

koboldcpp.py

Hello, I have the same problem as reported in #568 (while using /api/extra/generate/stream). The easiest way to reproduce this behavior is by starting a streaming connection and then simply dropping it, for example
```bash
timeout 2s curl --request POST \
--url http:/localhost:5001/api/extra/generate/stream \
--header 'Content-Type: application/json' \
--data '{ "prompt": "Niko the kobold stalked carefully down the alley, his small scaly figure obscured by a dusky cloak that fluttered lightly in the cold winter breeze." }'
```
Starting a new connection will then cause a crash.
One way to fix this is by handling BrokenPipeError. There is already a code for handling ConnectionAbortedError and I have tried to trigger it (without explicitly closing connection on a client) but failed. It's not …

Handle broken pipe errors during streaming

---

.github/workflows/kcpp-build-release-win-cuda.yaml

This PR downgrades CUDA to 11.4 to be in line with our previous releases, this results in a smaller binary and K80 compatibility.

CUDA 11.4 for Github CI

---

Makefile

This PR fixes the missing libraries in the CI environment, and ensures that all our users can access the required stubs as long as they are using our conda runtime.

Add Conda Runtime support for -lcuda

---

koboldcpp.py

This was causing issues when sending a request to the api without passing `rep_pen` = 1.0 explicitly.

Do not default to Repetition Penalty 1.1

---

Makefile

This pr adds a check ,already present in the upstream llama.cpp, that allows building the project using HIP on Debian Unstable since the required packages aren't located inside the /opt/rocm folder.
It's interesting to point out that the Debian Unstable team is currently building the HIP and ROCm packages with support for more devices than the ones officially supported by AMD so those ones are an amazing choice for whoever has an unsupported AMD gpu (my RX 5700XT is not officially supported by AMD but works great using Debian Unstable's packages).

Debian Unstable compatibility for HIP

---

koboldcpp.py

This works around a Win32 issue when piping output from a PyInstaller context, such as when doing so in a perl script or to an output file. Print statements from a Python context don't properly get output unless flushed.
This strategically flushes the print statements so no information is lost, though it may be better to flush all print statements in a Python context via a subroutine wrapper.
See also:
https://mail.python.org/pipermail/python-bugs-list/2004-August/024923.html
https://stackoverflow.com/a/466849
https://stackoverflow.com/q/62693079

Flush STDOUT when server starts listening.

---

Makefile
environment.yaml

This PR removes unneeded version definitions and an unneeded dependency. See my comments on the individual commits for more detailed explanations.

CUDA 12 support for the Conda Runtime

---

otherarch/sdcpp/stable-diffusion.cpp
otherarch/sdcpp/upscaler.cpp

Resolves following compilation errors on macOS with LLAMA_METAL=1
```
In file included from otherarch/sdcpp/sdtype_adapter.cpp:11:
./otherarch/sdcpp/stable-diffusion.cpp:127:9: error: use of undeclared identifier 'ggml_metal_log_set_callback'; did you mean 'ggml_backend_metal_log_set_callback'?
ggml_metal_log_set_callback(ggml_log_callback_default, nullptr);
^~~~~~~~~~~~~~~~~~~~~~~~~~~
ggml_backend_metal_log_set_callback
./ggml-metal.h:43:15: note: 'ggml_backend_metal_log_set_callback' declared here
GGML_API void ggml_backend_metal_log_set_callback(ggml_log_callback log_callback, void * user_data);
^
In file included from otherarch/sdcpp/sdtype_adapter.cpp:13:
./otherarch/sdcpp/upscaler.cpp:24:9: error: use of undeclared identifier 'ggml_metal_log_set_callback'; did you mean …
```

Resolve Metal compilation errors for sdcpp

---

koboldcpp.py

I was having trouble finding which of my `.safetensors` checkpoints for Stable Diffusion would actually work rather than fail to load. Since I was having to reload and try a different file a lot, I found it inconvenient to always navigate to the path where I keep those checkpoint files whenever I reloaded. Especially when my `.kcpps` was already pointing at a file in the correct directory, albeit at a file that didn't work.
This changes it so the 'Browse' buttons for files in the launcher will use the path from the current value (if there is one) to start the file dialog in. This also smooths out swapping LLM models when you already have a `.kcpps` file to tweak.
- In the launcher, if an existing value is set for a file value (e.g. Model), use that file's directory as the initial …

Set launcher file dialog initial paths from existing file values if they exist
